version: '3.7'
services:
  apache:
    image: httpd:latest
    ports:
      # <Port exposed> : < apache Port running inside container>
      - '80:80'
    expose:
      # Opens port 80 on the container
      - '80'
      # Where our data will be persisted
    volumes:
      - ./servidorfront/htdocs:/usr/local/apache2/htdocs
  basededatos:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'jmanuellh'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql
# Names our volume
volumes:
  mysql: